[package]
name = "eth_explo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
web3 = "0.18.0"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
serde_json = "1.0"
